
version: '3'

services:
   quonder-api:
    build:
      context: .
    container_name: quonder-api
    hostname: quonder-api
    restart: always
    ports:
      - 3000:3000
      - 5555:5555

volumes:
  db_data: {}