
version: '3'

services:
   template-api:
    build:
      context: .
    container_name: template-api
    hostname: template-api
    restart: always
    ports:
      - 3000:3000
      - 5555:5555

volumes:
  db_data: {}